language: go

go:
  - 1.9.x
  - 1.x

git:
  depth: 1

script:
  - go test -v -race ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
